### ISSUE TITLE
add single ion anisotropy K term (spin waves)

### ISSUE THREAD

**Issue by granazhs** [ILLGrenoble/takin#6]
examples with K term:
https://spinw.org/tutorials/14tutorial
https://spinw.org/tutorials/35tutorial

**Comment by tweber-ill** [comment]
Hi Markos!

I've been working on this on and off since your request.

In Takin/Magdyn you can add single-ion anisotropy terms by defining "self-couplings" in the "Couplings" tab: Set site 1 and site 2 equal to each other and the cell distance Δx=Δy=Δz=0. The anisotropy matrix can then be set using the Jxx, Jxy, ... columns.
